# -*- coding: utf-8 -*-
"""DASH-OP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhUIOJuKIhcs23dP5MiFgaiRf0mEHfxx
"""

!sudo apt-get update && sudo apt-get install ffmpeg yt-dlp -y && pip3 install paramiko gdown

import os
import random
import string
import subprocess
import json
import paramiko
import shutil
import requests
import re
from urllib.parse import urlparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import yt_dlp
import gdown

# ================= CONFIG =================
BASE_PATH = "./users/"
SFTP_HOST = "appserver.dev.8db3ca6d-1c90-4eab-acb4-5453c2a5add0.drush.in"
SFTP_PORT = 2222
SFTP_USERNAME = "dev.8db3ca6d-1c90-4eab-acb4-5453c2a5add0"
PRIVATE_KEY_PATH = "id_rsa"
REMOTE_BASE_PATH = "/code/dash/"
BASE_URL = "https://dev-cdn-satvik.pantheonsite.io/dash/"
TMDB_API_KEY = "303405b8c9e2eb7bcdadfed24baf5c18"
UPLOAD_WORKERS = 6          # parallel SFTP connections
USE_GPU_ENCODING = True     # try NVENC first, fallback to libx264 veryfast
FFMPEG_THREADS = "0"        # 0 = use all available cores

LANGUAGE_MAP = {
    "eng": "English", "en": "English", "spa": "Spanish", "es": "Spanish",
    "fra": "French", "fr": "French", "deu": "German", "de": "German",
    "ita": "Italian", "it": "Italian", "por": "Portuguese", "pt": "Portuguese",
    "rus": "Russian", "ru": "Russian", "nld": "Dutch", "nl": "Dutch",
    "swe": "Swedish", "sv": "Swedish", "nor": "Norwegian", "no": "Norwegian",
    "dan": "Danish", "da": "Danish", "fin": "Finnish", "fi": "Finnish",
    "pol": "Polish", "pl": "Polish", "tur": "Turkish", "tr": "Turkish",
    "gre": "Greek", "el": "Greek", "hun": "Hungarian", "hu": "Hungarian",
    "cze": "Czech", "cs": "Czech", "slk": "Slovak", "sk": "Slovak",
    "ukr": "Ukrainian", "uk": "Ukrainian", "bul": "Bulgarian", "bg": "Bulgarian",
    "ron": "Romanian", "ro": "Romanian", "hrv": "Croatian", "hr": "Croatian",
    "srp": "Serbian", "sr": "Serbian", "bos": "Bosnian", "bs": "Bosnian",
    "slv": "Slovenian", "sl": "Slovenian", "est": "Estonian", "et": "Estonian",
    "lav": "Latvian", "lv": "Latvian", "lit": "Lithuanian", "lt": "Lithuanian",
    "isl": "Icelandic", "is": "Icelandic",
    "jpn": "Japanese", "ja": "Japanese", "kor": "Korean", "ko": "Korean",
    "chi": "Chinese", "zh": "Chinese", "hin": "Hindi", "hi": "Hindi",
    "tam": "Tamil", "ta": "Tamil", "tel": "Telugu", "te": "Telugu",
    "kan": "Kannada", "kn": "Kannada", "mal": "Malayalam", "ml": "Malayalam",
    "ben": "Bengali", "bn": "Bengali", "mar": "Marathi", "mr": "Marathi",
    "urd": "Urdu", "ur": "Urdu", "guj": "Gujarati", "gu": "Gujarati",
    "pan": "Punjabi", "pa": "Punjabi", "ori": "Odia", "or": "Odia",
    "asm": "Assamese", "as": "Assamese", "sin": "Sinhala", "si": "Sinhala",
    "tha": "Thai", "th": "Thai", "vie": "Vietnamese", "vi": "Vietnamese",
    "ind": "Indonesian", "id": "Indonesian", "msa": "Malay", "ms": "Malay",
    "fil": "Filipino", "tl": "Filipino",
    "ara": "Arabic", "ar": "Arabic", "heb": "Hebrew", "he": "Hebrew",
    "fas": "Persian", "fa": "Persian", "amh": "Amharic", "am": "Amharic",
    "hau": "Hausa", "ha": "Hausa", "swa": "Swahili", "sw": "Swahili",
    "yor": "Yoruba", "yo": "Yoruba", "zul": "Zulu", "zu": "Zulu",
    "xho": "Xhosa", "xh": "Xhosa", "som": "Somali", "so": "Somali",
    "afr": "Afrikaans", "af": "Afrikaans",
    "sqi": "Albanian", "sq": "Albanian", "kat": "Georgian", "ka": "Georgian",
    "mkd": "Macedonian", "mk": "Macedonian", "tgl": "Tagalog",
    "jv": "Javanese", "jav": "Javanese", "su": "Sundanese", "sun": "Sundanese",
    "km": "Khmer", "kh": "Khmer", "lao": "Lao", "lo": "Lao",
    "my": "Burmese", "bur": "Burmese", "ne": "Nepali", "nep": "Nepali",
    "cy": "Welsh", "cym": "Welsh", "ga": "Irish", "gle": "Irish",
    "eo": "Esperanto", "epo": "Esperanto", "tlh": "Klingon", "xal": "Kalmyk",
    "krl": "Karelian", "kha": "Khasi", "mri": "Maori", "mi": "Maori",
    "sco": "Scots", "gd": "Scottish Gaelic", "gla": "Scottish Gaelic",
    "sna": "Shona", "sn": "Shona", "sm": "Samoan", "smo": "Samoan",
    "haw": "Hawaiian", "und": "Unknown",
}


def generate_folder_id():
    return "".join(random.choices(string.ascii_letters + string.digits, k=6))


# ================= DOWNLOAD =================
def download_video(url, user_folder):
    parsed_url = urlparse(url)
    domain = parsed_url.netloc.lower()
    print(f"Analyzing URL: {url}")

    if url.lower().endswith(('.mp4', '.mkv', '.mov', '.webm')):
        return download_direct_file(url, user_folder)

    ytdlp_domains = ['youtube.com', 'youtu.be', 'vimeo.com', 'dailymotion.com',
                      'twitch.tv', 'facebook.com', 'fb.watch', 'instagram.com',
                      'tiktok.com', 'twitter.com', 'x.com']
    if any(d in domain for d in ytdlp_domains):
        return download_with_ytdlp(url, user_folder)
    elif 'drive.google.com' in domain:
        return download_google_drive(url, user_folder)
    elif 'm3u8' in url.lower():
        return download_m3u8(url, user_folder)
    elif re.search(r'(mp4|mkv|mov|webm)', url.lower()):
        return download_direct_file(url, user_folder)
    else:
        return download_with_ytdlp(url, user_folder)


def download_google_drive(url, user_folder):
    print("Using Google Drive downloader...")
    file_id = re.search(r'[-\w]{25,}', url)
    if file_id:
        gdown.download(f'https://drive.google.com/uc?id={file_id.group(0)}',
                        os.path.join(user_folder, "input.mp4"), quiet=False)
        return os.path.join(user_folder, "input.mp4")
    print("Invalid Google Drive URL.")
    return None


def download_with_ytdlp(url, user_folder):
    print("Using yt-dlp downloader...")
    ydl_opts = {
        'outtmpl': f'{user_folder}/input.%(ext)s',
        'progress_hooks': [progress_hook],
        'format': 'bestvideo+bestaudio/best',
        'quiet': False,
        'no_warnings': False,
        'ignoreerrors': True,
        'concurrent_fragment_downloads': 8,   # speed: parallel fragment downloads
    }
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info_dict = ydl.extract_info(url, download=True)
            original_file = ydl.prepare_filename(info_dict)
            new_file = os.path.join(user_folder, "input.mkv")
            os.rename(original_file, new_file)
            return new_file
    except Exception as e:
        print(f"Error downloading video with yt-dlp: {str(e)}")
        return None


def download_direct_file(url, user_folder):
    print("Using direct file downloader...")
    output_file = os.path.join(user_folder, "input.mkv")
    try:
        with requests.get(url, stream=True) as r:
            r.raise_for_status()
            total_size = int(r.headers.get('content-length', 0))
            block_size = 1024 * 1024  # 1MB chunks: fewer syscalls, faster
            downloaded = 0
            with open(output_file, 'wb') as f:
                for chunk in r.iter_content(chunk_size=block_size):
                    if chunk:
                        f.write(chunk)
                        downloaded += len(chunk)
                        if total_size > 0:
                            percent = (downloaded / total_size) * 100
                            print(f"\rDownloading: {percent:.1f}%", end='')
        print("\nDirect download complete.")
        return output_file
    except Exception as e:
        print(f"Error downloading direct file: {str(e)}")
        return None


def download_m3u8(url, user_folder):
    print("Using m3u8/HLS downloader...")
    output_file = os.path.join(user_folder, "input.mkv")
    try:
        cmd = ["ffmpeg", "-y", "-i", url, "-c", "copy", "-bsf:a", "aac_adtstoasc", output_file]
        process = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                                    universal_newlines=True)
        process.wait()
        if process.returncode == 0:
            print("\nM3U8 download complete.")
            return output_file
        print(f"\nError downloading M3U8 stream. Return code: {process.returncode}")
        return None
    except Exception as e:
        print(f"Error downloading M3U8: {str(e)}")
        return None


def progress_hook(d):
    if d['status'] == 'downloading':
        print(f"\rDownloading: {d['_percent_str']} at {d['_speed_str']}", end='')


# ================= MEDIA INFO =================
def get_video_info(file_path):
    cmd = ["ffprobe", "-v", "error", "-show_streams", "-of", "json", file_path]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return json.loads(result.stdout)


def is_hevc_video(file_path):
    info = get_video_info(file_path)
    for stream in info.get("streams", []):
        if stream.get("codec_type") == "video" and stream.get("codec_name") in ["hevc", "h265", "h.265"]:
            return True
    return False


def has_subtitle_streams(video_info):
    for stream in video_info.get("streams", []):
        if stream.get("codec_type") == "subtitle":
            return True
    return False


# ================= AUDIO EXTRACTION (parallelized) =================
def extract_audio_tracks(user_folder, input_video):
    """Extract all audio tracks in parallel threads (ffmpeg is I/O + CPU bound,
    running multiple simultaneously speeds up multi-track videos significantly)."""
    info = get_video_info(input_video)
    lang_count = {}
    jobs = []

    for stream in info.get("streams", []):
        if stream.get("codec_type") == "audio":
            index = stream.get("index")
            lang = stream.get("tags", {}).get("language", f"und_{index}")
            codec_name = stream.get("codec_name", "aac")

            if lang in lang_count:
                lang_count[lang] += 1
                audio_file = f"{user_folder}/{lang}_{lang_count[lang]}.{codec_name}"
            else:
                lang_count[lang] = 0
                audio_file = f"{user_folder}/{lang}.{codec_name}"

            print(f"Audio track {index} detected with language: {lang} and codec: {codec_name}.")
            jobs.append((index, lang, codec_name, audio_file))

    audio_tracks = [None] * len(jobs)

    def run_job(job_idx, index, lang, codec_name, audio_file):
        if codec_name.lower() == "eac3":
            out_file = audio_file.replace(f".{codec_name}", ".aac")
            cmd = ["ffmpeg", "-y", "-i", input_video, "-map", f"0:{index}",
                   "-c:a", "aac", "-b:a", "192k", "-threads", FFMPEG_THREADS, out_file]
            subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            return job_idx, (out_file, lang)
        else:
            cmd = ["ffmpeg", "-y", "-i", input_video, "-map", f"0:{index}",
                   "-c:a", "copy", audio_file]
            subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            return job_idx, (audio_file, lang)

    with ThreadPoolExecutor(max_workers=min(4, max(1, len(jobs)))) as executor:
        futures = [executor.submit(run_job, i, *job) for i, job in enumerate(jobs)]
        for future in as_completed(futures):
            job_idx, result = future.result()
            audio_tracks[job_idx] = result

    return audio_tracks


# ================= SUBTITLE EXTRACTION (parallelized) =================
def extract_subtitle_tracks(user_folder, input_video):
    info = get_video_info(input_video)
    if not has_subtitle_streams(info):
        print("No subtitle tracks found in the video.")
        return []

    lang_count = {}
    jobs = []

    for stream in info.get("streams", []):
        if stream.get("codec_type") == "subtitle":
            index = stream.get("index")
            original_lang = stream.get("tags", {}).get("language", f"und_{index}")

            if original_lang in lang_count:
                lang_count[original_lang] += 1
                file_lang = f"{original_lang}{lang_count[original_lang]}"
            else:
                lang_count[original_lang] = 0
                file_lang = original_lang

            print(f"Subtitle track {index} detected with language: {original_lang}.")
            subtitle_file = f"{user_folder}/{file_lang}.vtt"

            display_name = LANGUAGE_MAP.get(original_lang.split('_')[0], original_lang)
            if lang_count[original_lang] > 0:
                display_name = f"{display_name} {lang_count[original_lang] + 1}"

            jobs.append((index, subtitle_file, original_lang, display_name))

    subtitle_tracks = [None] * len(jobs)

    def run_job(job_idx, index, subtitle_file, original_lang, display_name):
        subprocess.run(["ffmpeg", "-y", "-i", input_video, "-map", f"0:{index}", subtitle_file],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return job_idx, (subtitle_file, original_lang, display_name)

    with ThreadPoolExecutor(max_workers=min(4, max(1, len(jobs)))) as executor:
        futures = [executor.submit(run_job, i, *job) for i, job in enumerate(jobs)]
        for future in as_completed(futures):
            job_idx, result = future.result()
            subtitle_tracks[job_idx] = result

    return subtitle_tracks


# ================= VIDEO TRANSCODE (GPU-accelerated with fallback) =================
def _run_ffmpeg_with_progress(cmd, label="Processing"):
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                universal_newlines=True)
    duration = None
    for line in process.stdout:
        if duration is None and "Duration" in line:
            m = re.search(r"Duration: (\d+):(\d+):(\d+)", line)
            if m:
                h, mm, s = map(int, m.groups())
                duration = h * 3600 + mm * 60 + s
        if duration and "time=" in line:
            m = re.search(r"time=(\d+):(\d+):(\d+)", line)
            if m:
                h, mm, s = map(int, m.groups())
                current_time = h * 3600 + mm * 60 + s
                progress = min(100, int(current_time / duration * 100)) if duration else 0
                bar_length = 30
                filled = int(bar_length * progress / 100)
                bar = "#" * filled + "-" * (bar_length - filled)
                print(f"\r{label}: [{bar}] {progress}% complete", end='')
    process.wait()
    print()
    return process.returncode


def create_no_audio_video(user_folder, input_video):
    """Create a no-audio version, using GPU (NVENC) transcode for HEVC when available,
    falling back to a fast CPU preset. Non-HEVC videos are stream-copied (fastest)."""
    no_audio_video = f"{user_folder}/input1.mp4"

    if is_hevc_video(input_video):
        print("HEVC/H.265 video detected. Converting to H.264...")
        if USE_GPU_ENCODING:
            gpu_cmd = ["ffmpeg", "-y", "-i", input_video, "-c:v", "h264_nvenc",
                       "-preset", "p4", "-cq", "23", "-an", no_audio_video]
            returncode = _run_ffmpeg_with_progress(gpu_cmd, "GPU Transcoding")
            if returncode == 0:
                print("Converted using GPU (NVENC) acceleration.")
                return no_audio_video
            print("GPU encoding unavailable/failed, falling back to CPU...")

        cpu_cmd = ["ffmpeg", "-y", "-i", input_video, "-c:v", "libx264",
                   "-preset", "veryfast", "-crf", "23", "-threads", FFMPEG_THREADS,
                   "-an", no_audio_video]
        _run_ffmpeg_with_progress(cpu_cmd, "CPU Transcoding")
        print("Converted HEVC/H.265 to H.264 and removed audio.")
    else:
        print("Creating version with no audio (codec copy)...")
        subprocess.run(["ffmpeg", "-y", "-i", input_video, "-c:v", "copy", "-an", no_audio_video],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        print("Created no-audio version with original codec.")

    return no_audio_video


def encode_to_dash(user_folder, no_audio_video, audio_tracks):
    print("Encoding video to DASH format...")
    video_dash = f"{user_folder}/output.mpd"

    command = ["ffmpeg", "-y", "-i", no_audio_video]
    for audio_file, _ in audio_tracks:
        command.extend(["-i", audio_file])

    command.extend(["-map", "0:v:0", "-c:v", "copy"])

    for i, (audio_file, lang) in enumerate(audio_tracks):
        if audio_file.endswith('.opus'):
            codec = "libopus"
        elif audio_file.endswith('.mp3'):
            codec = "libmp3lame"
        else:
            codec = "aac"
        command.extend(["-map", f"{i+1}:a:0", "-c:a", codec, "-threads", FFMPEG_THREADS,
                         f"-metadata:s:a:{i}", f"language={lang}"])

    command.extend(["-f", "dash", video_dash])

    print("Generated ffmpeg command:")
    print(" ".join(command))
    print("\nStarting DASH encoding with progress...")

    returncode = _run_ffmpeg_with_progress(command, "DASH Encoding")

    if returncode == 0:
        print("DASH encoding complete.")
        return video_dash
    print("Error during DASH encoding.")
    return None


# ================= TMDB =================
def search_tmdb_movie(query):
    if query.isdigit():
        url = f"https://api.themoviedb.org/3/movie/{query}?api_key={TMDB_API_KEY}"
        response = requests.get(url)
        return [response.json()] if response.status_code == 200 else None

    url = f"https://api.themoviedb.org/3/search/movie?api_key={TMDB_API_KEY}&query={query}&include_adult=false"
    response = requests.get(url)
    if response.status_code == 200:
        results = response.json().get('results', [])
        if results:
            exact_matches = [r for r in results if r['title'].lower() == query.lower()]
            if exact_matches:
                return exact_matches
            return sorted(results, key=lambda x: x['popularity'], reverse=True)
    return None


def search_tmdb_tv(query):
    if query.isdigit():
        url = f"https://api.themoviedb.org/3/tv/{query}?api_key={TMDB_API_KEY}"
        response = requests.get(url)
        return [response.json()] if response.status_code == 200 else None

    url = f"https://api.themoviedb.org/3/search/tv?api_key={TMDB_API_KEY}&query={query}&include_adult=false"
    response = requests.get(url)
    if response.status_code == 200:
        results = response.json().get('results', [])
        if results:
            exact_matches = [r for r in results if r['name'].lower() == query.lower()]
            if exact_matches:
                return exact_matches
            return sorted(results, key=lambda x: x['popularity'], reverse=True)
    return None


def get_movie_details(movie_id):
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={TMDB_API_KEY}&append_to_response=credits,videos"
    response = requests.get(url)
    return response.json() if response.status_code == 200 else None


def get_tv_details(tv_id):
    url = f"https://api.themoviedb.org/3/tv/{tv_id}?api_key={TMDB_API_KEY}&append_to_response=credits,videos"
    response = requests.get(url)
    return response.json() if response.status_code == 200 else None


def get_tv_season(tv_id, season_number):
    url = f"https://api.themoviedb.org/3/tv/{tv_id}/season/{season_number}?api_key={TMDB_API_KEY}"
    response = requests.get(url)
    return response.json() if response.status_code == 200 else None


# ================= NEW HTML TEMPLATE (shared, redesigned) =================
def _base_style():
    return """
        :root {
            --bg-color: #0b0c10;
            --panel-color: rgba(20, 20, 25, 0.65);
            --accent-color: #6c5ce7;
            --accent-glow: rgba(108, 92, 231, 0.55);
            --text-color: #f5f5f7;
            --muted-color: #b3b3bd;
            --shadow-color: rgba(0,0,0,0.6);
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        html, body {
            background-color: var(--bg-color);
            color: var(--text-color);
            font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            overflow-x: hidden;
        }
        .hero {
            position: relative;
            width: 100%;
            min-height: 60vh;
            background-size: cover;
            background-position: center;
            display: flex;
            align-items: flex-end;
            padding: 40px 5%;
        }
        .hero::before {
            content: "";
            position: absolute;
            inset: 0;
            background: linear-gradient(180deg, rgba(11,12,16,0.2) 0%, rgba(11,12,16,0.85) 75%, var(--bg-color) 100%);
        }
        .glass-card {
            position: relative;
            z-index: 2;
            max-width: 820px;
            padding: 28px 32px;
            border-radius: 18px;
            background: var(--panel-color);
            backdrop-filter: blur(14px);
            -webkit-backdrop-filter: blur(14px);
            border: 1px solid rgba(255,255,255,0.08);
            box-shadow: 0 15px 40px var(--shadow-color);
            animation: fadeUp 0.6s ease-out;
        }
        @keyframes fadeUp {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }
        .hero-title {
            font-size: clamp(1.8rem, 4vw, 2.8rem);
            font-weight: 700;
            margin-bottom: 10px;
            letter-spacing: -0.5px;
        }
        .meta-info {
            display: flex;
            gap: 14px;
            flex-wrap: wrap;
            color: var(--muted-color);
            font-size: 0.9rem;
            margin-bottom: 14px;
        }
        .genre-tags { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px; }
        .genre-tag {
            background: rgba(108,92,231,0.15);
            border: 1px solid var(--accent-glow);
            color: var(--text-color);
            padding: 4px 14px;
            border-radius: 20px;
            font-size: 0.8rem;
            transition: all 0.25s ease;
        }
        .genre-tag:hover {
            background: var(--accent-color);
            box-shadow: 0 0 14px var(--accent-glow);
        }
        .overview {
            color: var(--muted-color);
            font-size: 1rem;
            max-width: 680px;
        }
        .container { width: 100%; max-width: 1200px; margin: 0 auto; padding: 30px 5%; }
        .player-shell {
            position: relative;
            width: 100%;
            border-radius: 16px;
            overflow: hidden;
            box-shadow: 0 20px 50px var(--shadow-color);
            background: #000;
        }
        .skeleton {
            position: absolute;
            inset: 0;
            z-index: 3;
            background: linear-gradient(100deg, #101014 30%, #1c1c22 50%, #101014 70%);
            background-size: 200% 100%;
            animation: shimmer 1.4s infinite;
            display: flex;
            align-items: center;
            justify-content: center;
            color: var(--muted-color);
            font-size: 0.9rem;
        }
        @keyframes shimmer {
            0% { background-position: 200% 0; }
            100% { background-position: -200% 0; }
        }
        .episode-strip {
            margin-top: 24px;
            display: flex;
            gap: 14px;
            overflow-x: auto;
            padding-bottom: 10px;
            scrollbar-width: thin;
        }
        .episode-card {
            flex: 0 0 220px;
            border-radius: 12px;
            overflow: hidden;
            background: rgba(255,255,255,0.04);
            border: 1px solid rgba(255,255,255,0.06);
            cursor: pointer;
            transition: transform 0.2s ease, box-shadow 0.2s ease;
        }
        .episode-card:hover {
            transform: translateY(-4px);
            box-shadow: 0 10px 25px var(--shadow-color);
        }
        .episode-card img { width: 100%; height: 120px; object-fit: cover; display: block; }
        .episode-card .ep-title {
            padding: 10px 12px;
            font-size: 0.85rem;
            color: var(--text-color);
        }
        .theme-toggle {
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 10;
            background: var(--panel-color);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255,255,255,0.1);
            color: var(--text-color);
            border-radius: 50%;
            width: 44px;
            height: 44px;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            font-size: 1.1rem;
        }
        body.light-mode {
            --bg-color: #f5f5f7;
            --panel-color: rgba(255,255,255,0.7);
            --text-color: #14141a;
            --muted-color: #55555f;
            --shadow-color: rgba(0,0,0,0.15);
        }
        @media (max-width: 768px) {
            .hero { min-height: 45vh; padding: 24px 5%; }
            .glass-card { padding: 20px; }
            .hero-title { font-size: 1.6rem; }
        }
    """


def _player_script(subtitle_tracks, title, image):
    tracks_json = ""
    if subtitle_tracks:
        entries = []
        for subtitle_file, _, display_name in subtitle_tracks:
            file_basename = os.path.basename(subtitle_file)
            entries.append(f'{{"file": "{file_basename}", "label": "{display_name}", "kind": "captions"}}')
        tracks_json = '"tracks": [' + ",".join(entries) + '],'

    return f"""
        var playerEl = document.getElementById('jwplayer-container');
        var skeleton = document.getElementById('skeleton-loader');
        jwplayer("jwplayer-container").setup({{
            "file": "output.mpd",
            "width": "100%",
            "aspectratio": "16:9",
            "title": "{title}",
            "image": "{image}",
            "autostart": false,
            "playbackRateControls": true,
            "preload": "metadata",
            {tracks_json}
            "skin": {{ "name": "netflix" }}
        }});
        jwplayer().on('ready', function() {{ if (skeleton) skeleton.style.display = 'none'; }});
        jwplayer().on('firstFrame', function() {{ if (skeleton) skeleton.style.display = 'none'; }});

        var toggle = document.getElementById('theme-toggle');
        if (toggle) {{
            toggle.addEventListener('click', function() {{
                document.body.classList.toggle('light-mode');
            }});
        }}
    """


def generate_movie_html(user_folder, subtitle_tracks, movie_data=None):
    title = "Stream"
    overview = ""
    backdrop = ""
    release_date = ""
    genres = []

    if movie_data:
        backdrop = f"https://image.tmdb.org/t/p/original{movie_data.get('backdrop_path', '')}"
        title = movie_data.get('title', 'Stream')
        overview = movie_data.get('overview', '')
        release_date = movie_data.get('release_date', '')
        genres = [genre['name'] for genre in movie_data.get('genres', [])]

    genre_html = "".join([f'<span class="genre-tag">{g}</span>' for g in genres])

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<script src="https://content.jwplatform.com/libraries/KB5zFt7A.js"></script>
<style>{_base_style()}</style>
</head>
<body>
<div class="theme-toggle" id="theme-toggle">&#9788;</div>
<div class="hero" style="background-image: url('{backdrop}');">
    <div class="glass-card">
        <h1 class="hero-title">{title}</h1>
        <div class="meta-info"><span>{release_date}</span></div>
        <div class="genre-tags">{genre_html}</div>
        <p class="overview">{overview}</p>
    </div>
</div>
<div class="container">
    <div class="player-shell">
        <div class="skeleton" id="skeleton-loader">Loading stream...</div>
        <div id="jwplayer-container"></div>
    </div>
</div>
<script>{_player_script(subtitle_tracks, title, backdrop)}</script>
</body>
</html>"""

    html_file_path = os.path.join(user_folder, "stream.html")
    with open(html_file_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    return html_file_path


def generate_tv_series_html(user_folder, subtitle_tracks, tv_data=None, season_data=None, episode_data=None):
    title = "Stream"
    overview = ""
    backdrop = ""
    first_air_date = ""
    genres = []
    episode_name = ""
    episode_image = ""

    if tv_data:
        backdrop = f"https://image.tmdb.org/t/p/original{tv_data.get('backdrop_path', '')}"
        title = tv_data.get('name', 'Stream')
        overview = tv_data.get('overview', '')
        first_air_date = tv_data.get('first_air_date', '')
        genres = [genre['name'] for genre in tv_data.get('genres', [])]

    if episode_data:
        episode_name = episode_data.get('name', '')
        episode_image = f"https://image.tmdb.org/t/p/w500{episode_data.get('still_path', '')}"

    genre_html = "".join([f'<span class="genre-tag">{g}</span>' for g in genres])

    episode_strip_html = ""
    if season_data and 'episodes' in season_data:
        cards = []
        for ep in season_data['episodes']:
            ep_img = f"https://image.tmdb.org/t/p/w300{ep.get('still_path', '')}" if ep.get('still_path') else backdrop
            cards.append(
                f'<div class="episode-card"><img src="{ep_img}" alt="{ep.get("name","")}">'
                f'<div class="ep-title">{ep.get("episode_number","")}. {ep.get("name","")}</div></div>'
            )
        episode_strip_html = f'<div class="episode-strip">{"".join(cards)}</div>'

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<script src="https://content.jwplatform.com/libraries/KB5zFt7A.js"></script>
<style>{_base_style()}</style>
</head>
<body>
<div class="theme-toggle" id="theme-toggle">&#9788;</div>
<div class="hero" style="background-image: url('{backdrop}');">
    <div class="glass-card">
        <h1 class="hero-title">{title}</h1>
        <div class="meta-info"><span>First aired: {first_air_date}</span></div>
        <div class="genre-tags">{genre_html}</div>
        <p class="overview">{overview}</p>
    </div>
</div>
<div class="container">
    <div class="player-shell">
        <div class="skeleton" id="skeleton-loader">Loading stream...</div>
        <div id="jwplayer-container"></div>
    </div>
    {episode_strip_html}
</div>
<script>{_player_script(subtitle_tracks, episode_name if episode_name else title, episode_image if episode_image else backdrop)}</script>
</body>
</html>"""

    html_file_path = os.path.join(user_folder, "stream.html")
    with open(html_file_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    return html_file_path


def generate_html_file(user_folder, subtitle_tracks, media_data=None, media_type=None, season_data=None, episode_data=None):
    if media_type == "movie":
        return generate_movie_html(user_folder, subtitle_tracks, media_data)
    elif media_type == "tv":
        return generate_tv_series_html(user_folder, subtitle_tracks, media_data, season_data, episode_data)
    else:
        return generate_movie_html(user_folder, subtitle_tracks)


# ================= UPLOAD (parallel SFTP) =================
UPLOAD_EXTENSIONS = ('.m4s', '.m4a', '.webm', '.mp3', '.ac3', '.eac3', '.ogg',
                      '.flac', '.mka', '.wav', '.pcm', '.dts', '.thd', '.amr',
                      '.html', '.mpd', '.vtt')


def _make_sftp_client():
    transport = paramiko.Transport((SFTP_HOST, SFTP_PORT))
    private_key = paramiko.RSAKey.from_private_key_file(PRIVATE_KEY_PATH)
    transport.connect(username=SFTP_USERNAME, pkey=private_key)
    sftp = paramiko.SFTPClient.from_transport(transport)
    return transport, sftp


def upload_files_to_sftp(local_folder, folder_id):
    """Upload all files in parallel using multiple SFTP connections for speed."""
    remote_folder_path = os.path.join(REMOTE_BASE_PATH, folder_id).replace("\\\\", "/")

    # Ensure remote directory exists (single connection, one-time setup)
    transport, sftp = _make_sftp_client()
    try:
        sftp.chdir(remote_folder_path)
    except IOError:
        sftp.mkdir(remote_folder_path)
    sftp.close()
    transport.close()

    files_to_upload = [
        os.path.join(root, f)
        for root, _, files in os.walk(local_folder)
        for f in files if f.endswith(UPLOAD_EXTENSIONS)
    ]
    total_files = len(files_to_upload)
    uploaded_files = [0]

    def upload_one(local_file_path):
        transport, sftp = _make_sftp_client()
        try:
            remote_file_path = os.path.join(remote_folder_path, os.path.basename(local_file_path)).replace("\\\\", "/")
            sftp.put(local_file_path, remote_file_path)
        finally:
            sftp.close()
            transport.close()
        uploaded_files[0] += 1
        print(f"\rUploaded {uploaded_files[0]}/{total_files} files", end='')

    with ThreadPoolExecutor(max_workers=min(UPLOAD_WORKERS, max(1, total_files))) as executor:
        futures = [executor.submit(upload_one, f) for f in files_to_upload]
        for future in as_completed(futures):
            future.result()

    print("\nUpload complete.")
    mpd_link = f"{BASE_URL}{folder_id}/output.mpd"
    html_link = f"{BASE_URL}{folder_id}/stream.html"
    print(f"MPD-Link: {mpd_link}")
    print(f"HTML-Link: {html_link}")


def clean_up(local_folder):
    shutil.rmtree(local_folder)
    print(f"Cleaned up local folder: {local_folder}")


# ================= MAIN =================
def main():
    print("=" * 50)
    print("Multi-Source Video Downloader and DASH Converter (Speed-Optimized)")
    print("=" * 50)
    print("Made By Satvik")
    print("=" * 50)
    print("Supported sources:")
    print("- YouTube, Vimeo, Dailymotion, Twitch")
    print("- Facebook, Instagram, TikTok, Twitter")
    print("- Direct MP4/MKV/MOV/WebM URLs")
    print("- M3U8 streams (HLS)")
    print("- Google Drive links")
    print("- And many more via yt-dlp...")
    print("=" * 50)

    url = input("Enter video URL: ")
    user_folder = os.path.join(BASE_PATH, generate_folder_id())
    os.makedirs(user_folder, exist_ok=True)

    print("Downloading video...")
    input_video = download_video(url, user_folder)

    if input_video is None:
        print("Download failed. Exiting.")
        clean_up(user_folder)
        return

    print("\nDownload complete.")

    no_audio_video = create_no_audio_video(user_folder, input_video)

    print("\nExtracting audio tracks (parallel)...")
    audio_tracks = extract_audio_tracks(user_folder, input_video)
    print("Audio extraction complete.")

    subtitle_tracks = extract_subtitle_tracks(user_folder, input_video)
    if subtitle_tracks:
        print("Subtitle extraction complete.")

    video_dash = encode_to_dash(user_folder, no_audio_video, audio_tracks)
    if video_dash is None:
        print("DASH encoding failed. Exiting.")
        clean_up(user_folder)
        return

    print("\nWould you like to search for TMDB information to enrich the HTML?")
    print("1. Yes, search for a movie")
    print("2. Yes, search for a TV show")
    print("3. No, skip TMDB integration")
    choice = input("Enter your choice (1/2/3): ")

    media_data = None
    media_type = None
    season_data = None
    episode_data = None

    if choice in ["1", "2"]:
        print("\nYou can search by:")
        print("1. Name (will show search results)")
        print("2. TMDB ID (will directly fetch details if valid)")
        search_method = input("Enter search method (1/2): ")

        if search_method == "1":
            query = input("Enter search query: ").strip()
            if not query:
                print("No query entered. Skipping TMDB integration.")
            else:
                if choice == "1":
                    results = search_tmdb_movie(query)
                    if results:
                        print("\nSearch results:")
                        for i, result in enumerate(results[:10]):
                            year = result.get('release_date', '')[:4] if result.get('release_date') else 'Unknown year'
                            print(f"{i + 1}. {result['title']} ({year})")
                        print("0. None of these (skip)")
                        selection = input("Select a movie (number) or 0 to skip: ")
                        if selection.isdigit() and 0 < int(selection) <= len(results):
                            media_data = get_movie_details(results[int(selection) - 1]['id'])
                            media_type = "movie"
                        else:
                            print("Skipping TMDB integration.")
                    else:
                        print("No results found. Skipping TMDB integration.")
                else:
                    results = search_tmdb_tv(query)
                    if results:
                        print("\nSearch results:")
                        for i, result in enumerate(results[:10]):
                            year = result.get('first_air_date', '')[:4] if result.get('first_air_date') else 'Unknown year'
                            print(f"{i + 1}. {result['name']} ({year})")
                        print("0. None of these (skip)")
                        selection = input("Select a TV show (number) or 0 to skip: ")
                        if selection.isdigit() and 0 < int(selection) <= len(results):
                            media_data = get_tv_details(results[int(selection) - 1]['id'])
                            media_type = "tv"
                            if media_data and 'seasons' in media_data:
                                seasons = media_data['seasons']
                                print("\nAvailable seasons:")
                                for i, season in enumerate(seasons):
                                    print(f"{i + 1}. {season['name']} ({season.get('episode_count', 0)} episodes)")
                                print("0. Skip season selection")
                                season_selection = input("Select a season (number) or 0 to skip: ")
                                if season_selection.isdigit() and 0 < int(season_selection) <= len(seasons):
                                    season_number = seasons[int(season_selection) - 1]['season_number']
                                    season_data = get_tv_season(media_data['id'], season_number)
                                    if season_data and 'episodes' in season_data:
                                        episodes = season_data['episodes']
                                        print("\nAvailable episodes:")
                                        for i, episode in enumerate(episodes):
                                            print(f"{i + 1}. {episode['name']}")
                                        print("0. Skip episode selection")
                                        episode_selection = input("Select an episode (number) or 0 to skip: ")
                                        if episode_selection.isdigit() and 0 < int(episode_selection) <= len(episodes):
                                            episode_data = episodes[int(episode_selection) - 1]
                                        else:
                                            print("Skipping episode selection.")
                                    else:
                                        print("No episodes found for this season.")
                                else:
                                    print("Skipping season selection.")
                            else:
                                print("No seasons found for this show.")
                        else:
                            print("Skipping TMDB integration.")
                    else:
                        print("No results found. Skipping TMDB integration.")
        elif search_method == "2":
            tmdb_id = input("Enter TMDB ID: ").strip()
            if not tmdb_id.isdigit():
                print("Invalid TMDB ID (must be numeric). Skipping TMDB integration.")
            else:
                if choice == "1":
                    media_data = get_movie_details(tmdb_id)
                    if media_data:
                        media_type = "movie"
                        print(f"Found movie: {media_data.get('title', 'Unknown')}")
                    else:
                        print("No movie found with that ID. Skipping TMDB integration.")
                else:
                    media_data = get_tv_details(tmdb_id)
                    if media_data:
                        media_type = "tv"
                        print(f"Found TV show: {media_data.get('name', 'Unknown')}")
                        if 'seasons' in media_data:
                            seasons = media_data['seasons']
                            print("\nAvailable seasons:")
                            for i, season in enumerate(seasons):
                                print(f"{i + 1}. {season['name']} ({season.get('episode_count', 0)} episodes)")
                            print("0. Skip season selection")
                            season_selection = input("Select a season (number) or 0 to skip: ")
                            if season_selection.isdigit() and 0 < int(season_selection) <= len(seasons):
                                season_number = seasons[int(season_selection) - 1]['season_number']
                                season_data = get_tv_season(media_data['id'], season_number)
                                if season_data and 'episodes' in season_data:
                                    episodes = season_data['episodes']
                                    print("\nAvailable episodes:")
                                    for i, episode in enumerate(episodes):
                                        print(f"{i + 1}. {episode['name']}")
                                    print("0. Skip episode selection")
                                    episode_selection = input("Select an episode (number) or 0 to skip: ")
                                    if episode_selection.isdigit() and 0 < int(episode_selection) <= len(episodes):
                                        episode_data = episodes[int(episode_selection) - 1]
                                    else:
                                        print("Skipping episode selection.")
                                else:
                                    print("No episodes found for this season.")
                            else:
                                print("Skipping season selection.")
                        else:
                            print("No seasons found for this show.")
                    else:
                        print("No TV show found with that ID. Skipping TMDB integration.")
        else:
            print("Invalid search method. Skipping TMDB integration.")
    elif choice == "3":
        print("Skipping TMDB integration.")
    else:
        print("Invalid choice. Skipping TMDB integration.")

    print("\nGenerating HTML file...")
    html_file = generate_html_file(user_folder, subtitle_tracks, media_data, media_type, season_data, episode_data)
    print("HTML file generated.")

    print("\nUploading files to SFTP server (parallel)...")
    folder_id = os.path.basename(user_folder)
    upload_files_to_sftp(user_folder, folder_id)

    print("\nCleaning up local files...")
    clean_up(user_folder)

    print("\nProcess completed successfully!")
    print("=" * 50)


if __name__ == "__main__":
    main()